version: 1.0.{build}
configuration: Release

environment:
  nodejs_version: "5.0"
install:
  - ps: Install-Product node $env:nodejs_version

# scripts to run before build
before_build:
- cmd: >-
    nuget restore PoorClaresAngular.sln

    node -v

    npm -v

    npm install -g gulp

build_script:
- cmd: >-
    msbuild PoorClaresAngular.sln /p:Configuration=Release /verbosity:quiet /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    cd PoorClaresAngular

    msbuild PoorClaresAngular.csproj /t:Package /p:PackageLocation=..\PoorClaresAngular.zip

    cd ..

artifacts:
- path: PoorClaresAngular.zip
  name: WebApplication
  type: WebDeployPackage

before_test:
- ps: >-
    cd PoorClaresAngular

    npm run test

    cd ../

    ./registerTestResults.ps1

deploy:
- provider: WebDeploy
  server: https://poorclareses6.scm.azurewebsites.net:443/msdeploy.axd?site=poorclareses6
  website: poorclareses6
  username:
    secure: havqx5eDApXZM/pv9T5Na4ghKRUS0CctLvqAD8rvwmE=
  password:
    secure: OfdyJRli28SPmISEI9TFL6IrCMr5DY1iNkXfRP2NGxSk2ATEwb4q9W+Bm4P9G3qG3L5JSChcYMAm4Cb2dnlxWQ==
  remove_files: true
